MESSAGE_START = """__Bonjour et bienvenue__ ðŸ‘‹

Je suis un agent conversationnel expÃ©rimental, conÃ§u pour rÃ©pondre Ã  vos questions Ã  partir des donnÃ©es et publications disponibles sur le site [insee.fr](https://www.insee.fr). 

N'hÃ©sitez pas Ã  me poser vos questions sur les nombreux thÃ¨mes couverts par l'Insee ðŸ“Š (dÃ©mographie, Ã©conomie, statistiques rÃ©gionales, etc.) 

> âš ï¸ **Disclaimer** :  
> Je suis encore en phase de test. Mes rÃ©ponses sont gÃ©nÃ©rÃ©es automatiquement Ã  partir des informations accessibles sur le site de lâ€™INSEE, mais elles peuvent comporter des approximations ou ne pas Ãªtre parfaitement Ã  jour.
> 
> N'hÃ©sitez pas Ã  utiliser les boutons d'Ã©valuation proposÃ©s aprÃ¨s une rÃ©ponse pour aider les gentils humains qui me dÃ©veloppent Ã  m'amÃ©liorer. 
>
> Mon but est de vous aider Ã  trouver de l'information fiable sur le site [insee.fr](https://www.insee.fr). Cependant, pour toute dÃ©cision importante, vÃ©rifiez l'information sur le [site de l'Insee](https://www.insee.fr).

"""

MESSAGE_PAST_CONVERSATION = "### ðŸ’¬ Past Conversations"
MESSAGE_PAST_CONVERSATION_ANON = "### To get conversation history, change the username"
